guide/customization/page-style.md

fix: fix variable name in guide

---

guide/README.md
webpack.config.js

fix: use default browser support preset

---

src/state/__tests__/index.js
src/state/index.js

fix: properly create nested proxies

---

examples/cloak-of-darkness.txt

fix: fix deadend

---

src/template/__tests__/render-inserts.js
src/template/render-inserts.js

fix: check for backslashed quotes

---

src/display/transitions.js

fix: put contents of no transition in container

---

examples/sound.txt
guide/multimedia/audio.md
src/template/inserts/ambient-sound.js

Allow stopping ambient sound

---

src/style/__tests__/parse.js
src/style/parse.js

fix: parse dotted decimal sizes correctly

---

package-lock.json
package.json
src/state/__tests__/index.js
src/state/index.js

Fix nested lookups

---

src/__tests__/story.test.js
src/state/index.js
src/story.js

Resolves #56
This will cause saved story progress to be lost if a story was published before this change,
and then republished after this change. I'm not marking this as a breaking
change because the author experience is identical, but it will get flagged
in release notes.

fix: use IFID in state persistence key

---

examples/active-link-restart.txt
src/style/__tests__/parse.js
src/style/parse.js

fix: handle undefined style values

---

src/backstage/style/config.jsx

fix: update config text block when state changes

---

src/editor-extensions/twine/codemirror-commands.js

Fix toolbar inserts

---

package-lock.json
src/runtime/template/__tests__/render.js
src/runtime/template/render.js

Fix logging in render

---

examples/input.txt
src/runtime/template/inserts/cycling-link.js
src/runtime/template/inserts/menu.js
src/runtime/util/htmlify.js

fix: allow numeric choices in cycling links and dropdown menus

---

.gitignore
demo/javascript.twee
demo/tests/javascript.spec.ts
src/runtime/template/modifiers/__tests__/css.test.ts
src/runtime/template/modifiers/__tests__/javascript.test.ts
src/runtime/template/modifiers/css.ts
src/runtime/template/modifiers/javascript.ts

fix: Process JavaScript and CSS as raw

---

guide/src/customization/page-style.md

docs: fix style-related config mentions

---

demo/start.twee
demo/tests/transitions.spec.ts
demo/transitions.twee
src/runtime/display/transitions.ts

fix: fadeInOut transition

---

src/twine-extensions/__tests__/parse-references.test.ts
src/twine-extensions/parse-references.ts

fix: parse labeled link as reference

---

src/twine-extensions/codemirror-commands.ts

fix: fix insertRevealTextLink command

---

src/runtime/display/marginals.css

fix: styling of header border

---

src/runtime/template/custom-elements/passage-link.ts

fix: make passage links focusable

---

src/runtime/display/custom-elements/__tests__/state-css-variables.test.ts
src/runtime/display/custom-elements/__tests__/state-dark-theme-css-overrides.test.ts
src/runtime/display/custom-elements/state-css-variables.ts
src/runtime/display/custom-elements/state-dark-theme-css-overrides.ts

Handle top-level style changes correctly

---

src/runtime/template/__tests__/render-inserts.test.ts
src/runtime/template/render-inserts.ts

Allow { inside quotation marks in an insert

---

guide/src/modifiers-and-inserts/link-inserts.md

docs: fix link
